import { RecordingMode, TermHelpVisibility } from '../types/models';

export type GlossaryCategory = 'recipe' | 'basket' | 'puck_prep' | 'extraction' | 'diagnosis' | 'bes876';
export type GlossaryLevel = 'beginner' | 'intermediate' | 'advanced';

export type GlossaryEntry = {
  id: string;
  term: string;
  koTerm: string;
  aliases?: readonly string[];
  level: GlossaryLevel;
  category: GlossaryCategory;
  shortDefinition: string;
  whyItMatters: string;
  whatToRecord?: readonly string[];
  commonMistake?: string;
  bes876Note?: string;
  relatedTerms?: readonly string[];
  relatedResourceTags?: readonly string[];
};

export const GLOSSARY_ENTRIES = {
  dose: {
    id: 'dose',
    term: 'Dose',
    koTerm: '도징량',
    aliases: ['투입량', '원두량'],
    level: 'beginner',
    category: 'recipe',
    shortDefinition: '바스켓에 넣는 분쇄 원두의 무게입니다.',
    whyItMatters: '도징량이 바뀌면 같은 분쇄도와 시간이어도 맛과 흐름이 달라집니다.',
    whatToRecord: ['실제로 바스켓에 들어간 원두 g', '자동 도징을 썼는지 여부', '바스켓 종류'],
    commonMistake: '머신이 맞춰준 양을 그대로 믿고 실제 무게를 재지 않는 것입니다.',
    bes876Note: 'Impress 자동 도징을 써도 비교 기록에는 저울로 잰 도징량이 가장 안정적입니다.',
    relatedTerms: ['yield', 'grind_size'],
    relatedResourceTags: ['도징', 'AUTO', 'MANUAL', '다이얼인', '워크스루', '매뉴얼'],
  },
  yield: {
    id: 'yield',
    term: 'Yield',
    koTerm: '수율',
    aliases: ['추출량', '아웃'],
    level: 'beginner',
    category: 'recipe',
    shortDefinition: '컵에 나온 에스프레소의 무게입니다.',
    whyItMatters: '수율은 농도와 밸런스를 판단하는 핵심값입니다. 같은 도징량이라도 수율이 늘면 더 묽고 길게 추출됩니다.',
    whatToRecord: ['컵에 나온 에스프레소 g', '가능하면 크레마 포함 전체 무게', '목표 수율과 실제 수율의 차이'],
    commonMistake: 'ml 눈금으로만 판단하는 것입니다. 에스프레소는 g으로 재야 반복 비교가 쉽습니다.',
    bes876Note: '처음에는 18g in, 36g out을 출발점으로 둘 수 있지만 원두와 취향에 따라 달라질 수 있습니다.',
    relatedTerms: ['dose', 'brew_time'],
    relatedResourceTags: ['수율', '샷볼륨', '다이얼인', '워크스루'],
  },
  brew_time: {
    id: 'brew_time',
    term: 'Brew time',
    koTerm: '추출 시간',
    aliases: ['시간', '샷 시간'],
    level: 'beginner',
    category: 'recipe',
    shortDefinition: '추출을 시작한 뒤 목표 수율에 도달할 때까지 걸린 시간입니다.',
    whyItMatters: '시간은 분쇄도와 흐름 상태를 판단하는 빠른 신호입니다.',
    whatToRecord: ['총 추출 시간 초', '첫 방울 시간이 보이면 선택 기록', '타이머/저울/추정 중 어떤 기준인지'],
    commonMistake: '시간만 보고 맛을 판단하는 것입니다. 도징량과 수율을 함께 봐야 합니다.',
    bes876Note: '25-35초는 출발점으로 쓸 수 있지만, 원두와 바스켓에 따라 좋은 범위가 달라집니다.',
    relatedTerms: ['yield', 'grind_size', 'first_drip'],
    relatedResourceTags: ['샷볼륨', '다이얼인', '워크스루', '입문'],
  },
  grind_size: {
    id: 'grind_size',
    term: 'Grind size',
    koTerm: '분쇄도',
    aliases: ['그라인드', '분쇄 굵기'],
    level: 'beginner',
    category: 'recipe',
    shortDefinition: '커피를 얼마나 곱거나 굵게 갈았는지를 뜻합니다.',
    whyItMatters: '너무 굵으면 빠르고 묽게 흐르고, 너무 고우면 느리거나 막힐 수 있습니다.',
    whatToRecord: ['BES876 외부 다이얼 1-25 값', '내부 버를 바꿨다면 내부 버 값', '분쇄도 다이얼 사진'],
    commonMistake: '맛이 안 맞을 때 여러 변수를 한꺼번에 바꾸는 것입니다. 먼저 분쇄도 하나만 바꿔 보세요.',
    bes876Note: 'BES876 외부 다이얼은 숫자가 작을수록 더 곱게 가는 기준으로 기록하면 비교하기 쉽습니다.',
    relatedTerms: ['dose', 'brew_time'],
    relatedResourceTags: ['다이얼인', 'AUTO', '워크스루', '제품', '매뉴얼'],
  },
  single_wall: {
    id: 'single_wall',
    term: 'Single wall basket',
    koTerm: '싱글월 바스켓',
    aliases: ['비가압 바스켓'],
    level: 'beginner',
    category: 'basket',
    shortDefinition: '바닥 구멍이 일반적으로 뚫려 있는 비가압 바스켓입니다.',
    whyItMatters: '원두 신선도, 분쇄도, 퍽 준비 영향을 그대로 보여주기 때문에 다이얼인에 적합합니다.',
    whatToRecord: ['싱글월 1컵/2컵 여부', '도징량', '분쇄도', '수율과 시간'],
    commonMistake: '듀얼월에서 쓰던 분쇄도를 그대로 옮기는 것입니다. 두 바스켓은 흐름이 다릅니다.',
    bes876Note: '신선한 원두와 저울 기록을 쓰기 시작했다면 싱글월이 학습에 더 좋습니다.',
    relatedTerms: ['dual_wall', 'grind_size'],
    relatedResourceTags: ['매뉴얼', '제품', '워크스루', '입문'],
  },
  dual_wall: {
    id: 'dual_wall',
    term: 'Dual wall basket',
    koTerm: '듀얼월 바스켓',
    aliases: ['가압 바스켓'],
    level: 'beginner',
    category: 'basket',
    shortDefinition: '압력을 보정해 크레마와 저항을 어느 정도 만들어주는 바스켓입니다.',
    whyItMatters: '초보자에게 안정적이지만 실제 분쇄도와 퍽 준비 문제를 가릴 수 있습니다.',
    whatToRecord: ['듀얼월 1컵/2컵 여부', '원두 신선도', '맛이 묽은지 쓴지'],
    commonMistake: '듀얼월에서 괜찮았다고 싱글월도 같은 세팅이 맞을 거라 보는 것입니다.',
    bes876Note: '오래된 원두나 분쇄가 애매할 때는 도움이 되지만, 세밀한 다이얼인은 싱글월 기준이 더 명확합니다.',
    relatedTerms: ['single_wall', 'yield'],
    relatedResourceTags: ['매뉴얼', '제품', '워크스루', '입문'],
  },
  wdt: {
    id: 'wdt',
    term: 'WDT',
    koTerm: 'WDT',
    aliases: ['분배', '침칠'],
    level: 'intermediate',
    category: 'puck_prep',
    shortDefinition: '얇은 바늘 도구로 분쇄 원두의 뭉침을 풀고 고르게 분산시키는 작업입니다.',
    whyItMatters: '뭉친 원두가 있으면 물이 약한 곳으로 몰려 채널링이 생기기 쉽습니다.',
    whatToRecord: ['WDT 사용 여부', '채널링 의심 여부', '바텀리스에서 튐이 있었는지'],
    commonMistake: '너무 깊고 거칠게 저어 표면을 더 불균일하게 만드는 것입니다.',
    bes876Note: '내장 그라인더를 쓸 때 뭉침이 보이면 싱글월 바스켓에서 특히 도움이 될 수 있습니다.',
    relatedTerms: ['channeling', 'leveling'],
    relatedResourceTags: ['다이얼인', '워크스루', '문제해결', '입문'],
  },
  leveling: {
    id: 'leveling',
    term: 'Leveling',
    koTerm: '레벨링',
    aliases: ['수평 맞춤'],
    level: 'intermediate',
    category: 'puck_prep',
    shortDefinition: '탬핑 전 커피 표면을 평평하게 정리하는 과정입니다.',
    whyItMatters: '표면이 기울어지면 물이 한쪽으로 더 잘 지나가 추출이 흔들릴 수 있습니다.',
    whatToRecord: ['레벨링 사용 여부', '탬핑 후 퍽 표면 사진', '채널링 흔적'],
    commonMistake: '레벨링 도구로 커피를 과하게 눌러 실제 도징 높이를 바꾸는 것입니다.',
    bes876Note: 'Impress 탬핑을 써도 분배가 한쪽으로 몰렸다면 레벨링과 WDT를 같이 확인하세요.',
    relatedTerms: ['tamping', 'wdt'],
    relatedResourceTags: ['다이얼인', '워크스루', '문제해결', '입문'],
  },
  tamping: {
    id: 'tamping',
    term: 'Tamping',
    koTerm: '탬핑',
    aliases: ['압착'],
    level: 'beginner',
    category: 'puck_prep',
    shortDefinition: '분쇄 원두를 바스켓 안에서 평평하고 일정하게 눌러주는 작업입니다.',
    whyItMatters: '탬핑이 기울거나 매번 다르면 같은 레시피도 흐름이 달라집니다.',
    whatToRecord: ['탬핑이 안정적이었는지', '탬핑 후 퍽 사진', 'Razor 트리밍 여부'],
    commonMistake: '힘을 매번 다르게 주거나 포터필터가 기울어진 상태로 누르는 것입니다.',
    bes876Note: 'Impress 레버는 일관성을 도와주지만, 원두 분배가 나쁘면 탬핑만으로 해결되지 않습니다.',
    relatedTerms: ['leveling', 'channeling'],
    relatedResourceTags: ['매뉴얼', '워크스루', '다이얼인', '입문'],
  },
  puck_screen: {
    id: 'puck_screen',
    term: 'Puck screen',
    koTerm: '퍽스크린',
    aliases: ['스크린'],
    level: 'intermediate',
    category: 'puck_prep',
    shortDefinition: '커피 퍽 위에 얹는 얇은 금속 스크린입니다.',
    whyItMatters: '물을 조금 더 고르게 분산시키고 그룹헤드 오염을 줄이는 데 도움을 줄 수 있습니다.',
    whatToRecord: ['퍽스크린 사용 여부', '도징량 변화', '추출 시간 변화'],
    commonMistake: '퍽스크린을 추가했는데 도징 높이를 그대로 두어 헤드스페이스가 부족해지는 것입니다.',
    bes876Note: '사용하면 퍽 높이가 달라질 수 있으니 같은 원두에서는 사용 여부를 꼭 기록하세요.',
    relatedTerms: ['tamping', 'channeling'],
    relatedResourceTags: ['다이얼인', '문제해결', '워크스루'],
  },
  preinfusion: {
    id: 'preinfusion',
    term: 'Preinfusion',
    koTerm: '프리인퓨전',
    aliases: ['프리', '사전 적심'],
    level: 'intermediate',
    category: 'extraction',
    shortDefinition: '본격적으로 커피가 나오기 전에 물이 커피 퍽을 살짝 적시는 구간입니다.',
    whyItMatters: '초반 흐름이나 채널링을 자세히 비교할 때 도움이 되지만, 처음에는 몰라도 괜찮은 선택 기록입니다.',
    whatToRecord: ['초보자는 비워두기', '익숙해지면 프리인퓨전 종료 시간 초', '총 추출 시간과 첫 방울 시간'],
    commonMistake: '프리인퓨전을 꼭 기록해야 한다고 느끼는 것입니다. 처음에는 총 추출 시간과 첫 방울만으로 충분합니다.',
    bes876Note: 'BES876에서는 “프리 종료” 버튼을 모르면 누르지 않아도 됩니다. 나중에 흐름을 더 자세히 보고 싶을 때만 기록하세요.',
    relatedTerms: ['first_drip', 'brew_time'],
    relatedResourceTags: ['샷볼륨', '온도', '매뉴얼', '워크스루'],
  },
  first_drip: {
    id: 'first_drip',
    term: 'First drip',
    koTerm: '첫 방울',
    aliases: ['첫 추출'],
    level: 'intermediate',
    category: 'extraction',
    shortDefinition: '추출을 시작한 뒤 커피가 처음 떨어지는 시점입니다.',
    whyItMatters: '첫 방울이 너무 빠르거나 늦으면 분쇄도, 도징량, 퍽 준비를 다시 볼 신호가 됩니다.',
    whatToRecord: ['첫 방울 시간 초', '총 추출 시간', '압력 게이지 피크'],
    commonMistake: '첫 방울이 조금 달라졌다고 바로 여러 세팅을 동시에 바꾸는 것입니다.',
    bes876Note: 'BES876에서는 타이머 랩으로 첫 방울을 찍고, 저장 전 모르면 비워둬도 됩니다.',
    relatedTerms: ['preinfusion', 'brew_time'],
    relatedResourceTags: ['샷볼륨', '다이얼인', '워크스루'],
  },
  channeling: {
    id: 'channeling',
    term: 'Channeling',
    koTerm: '채널링',
    aliases: ['물길', '분사'],
    level: 'intermediate',
    category: 'diagnosis',
    shortDefinition: '물이 커피 퍽 전체가 아니라 약한 경로로 몰려 흐르는 현상입니다.',
    whyItMatters: '일부는 과소추출, 일부는 과다추출되어 시고 떫고 묽은 맛이 같이 날 수 있습니다.',
    whatToRecord: ['바텀리스에서 튐이 있었는지', '한쪽으로만 흐르는지', '맛이 묽거나 떫은지'],
    commonMistake: '채널링을 무조건 분쇄도 문제로만 보는 것입니다. WDT, 레벨링, 탬핑도 함께 봐야 합니다.',
    bes876Note: 'Impress 탬핑을 써도 분배가 나쁘면 채널링이 생길 수 있습니다.',
    relatedTerms: ['wdt', 'tamping'],
    relatedResourceTags: ['문제해결', '다이얼인', '워크스루', '입문'],
  },
  bottomless_check: {
    id: 'bottomless_check',
    term: 'Bottomless check',
    koTerm: '바텀리스 확인',
    aliases: ['바텀리스 포터필터'],
    level: 'advanced',
    category: 'diagnosis',
    shortDefinition: '바닥이 열린 포터필터로 추출 흐름과 분사를 직접 확인하는 진단입니다.',
    whyItMatters: '채널링, 한쪽 흐름, 초반 분사 같은 문제를 눈으로 보기 좋습니다.',
    whatToRecord: ['분사 튐 여부', '한쪽 흐름 여부', '추출 컵 사진 또는 영상 메모'],
    commonMistake: '바텀리스에서 조금만 튀어도 모든 샷이 실패라고 보는 것입니다. 맛과 시간도 함께 보세요.',
    bes876Note: 'BES876 기본 포터필터와 다른 액세서리를 쓸 때는 바스켓과 도징량도 같이 기록하세요.',
    relatedTerms: ['channeling', 'tamping'],
    relatedResourceTags: ['문제해결', '다이얼인', '워크스루'],
  },
  dose_gauge: {
    id: 'dose_gauge',
    term: 'Dose gauge',
    koTerm: '도즈 게이지',
    aliases: ['Under', 'Ideal', 'A Bit More', 'Over'],
    level: 'beginner',
    category: 'bes876',
    shortDefinition: 'BES876 Impress가 도징량과 탬핑 후 높이를 표시하는 게이지입니다.',
    whyItMatters: 'AUTO 도징을 쓸 때 이번 샷이 부족, 적정, 추가 필요, 과다 중 어디였는지 남길 수 있습니다.',
    whatToRecord: ['Under/Ideal/A Bit More/Over 위치', 'A Bit More 사용 여부', '도즈 게이지 사진'],
    commonMistake: '게이지가 Ideal이면 무조건 맛도 맞는다고 보는 것입니다. 수율과 시간도 필요합니다.',
    bes876Note: '도즈 게이지는 편의 기능이고, 다이얼인 비교에는 실제 도징량 g이 더 정확합니다.',
    relatedTerms: ['dose', 'a_bit_more'],
    relatedResourceTags: ['AUTO', '도징', '다이얼인', '매뉴얼', '워크스루'],
  },
  a_bit_more: {
    id: 'a_bit_more',
    term: 'A Bit More',
    koTerm: 'A Bit More',
    aliases: ['조금 더'],
    level: 'beginner',
    category: 'bes876',
    shortDefinition: 'BES876 AUTO 도징에서 원두가 조금 부족할 때 추가 도징을 유도하는 표시입니다.',
    whyItMatters: '자동 도징이 매번 얼마나 보정되는지 보면 원두 상태와 그라인더 흐름을 추적할 수 있습니다.',
    whatToRecord: ['A Bit More 표시 여부', '추가 후 실제 도징량 g', 'Razor 트리밍 여부'],
    commonMistake: 'A Bit More가 떴다고 무조건 분쇄도를 바꾸는 것입니다. 먼저 실제 도징량을 확인하세요.',
    bes876Note: '같은 원두에서 계속 뜬다면 도징 리셋이나 원두 보충 상태도 확인해 보세요.',
    relatedTerms: ['dose_gauge', 'dose'],
    relatedResourceTags: ['AUTO', '도징', '다이얼인', 'MANUAL', '매뉴얼'],
  },
  razor_trim: {
    id: 'razor_trim',
    term: 'Razor trim',
    koTerm: 'Razor 트리밍',
    aliases: ['레이저 도구'],
    level: 'intermediate',
    category: 'bes876',
    shortDefinition: 'BES876에 포함된 Razor 도구로 퍽 높이를 일정하게 깎아 맞추는 작업입니다.',
    whyItMatters: '도징량이 높거나 퍽이 샤워스크린에 닿는 상황을 줄이는 데 도움이 됩니다.',
    whatToRecord: ['Razor 사용 여부', '깎인 원두가 많았는지', '탬핑 후 퍽 사진'],
    commonMistake: '매번 많이 깎이는데도 도징량을 그대로 두는 것입니다.',
    bes876Note: 'Razor가 자주 필요하면 도징량, 바스켓, 퍽스크린 사용 여부를 같이 확인하세요.',
    relatedTerms: ['dose', 'tamping'],
    relatedResourceTags: ['도징', '매뉴얼', '워크스루', '입문'],
  },
  pressure_gauge: {
    id: 'pressure_gauge',
    term: 'Pressure gauge',
    koTerm: '압력 게이지',
    aliases: ['압력계'],
    level: 'intermediate',
    category: 'bes876',
    shortDefinition: '추출 중 머신 전면 바늘이 보여주는 압력 범위입니다.',
    whyItMatters: '낮음, 에스프레소 범위, 높음 중 어디에 있었는지 흐름 문제를 해석하는 보조 신호가 됩니다.',
    whatToRecord: ['피크 압력 구간', '압력 게이지 사진', '총 추출 시간과 수율'],
    commonMistake: '압력만 정상 범위면 맛도 정상이라고 보는 것입니다.',
    bes876Note: '압력이 낮으면 너무 굵거나 도징이 낮을 수 있고, 너무 높으면 너무 곱거나 막힘이 있을 수 있습니다.',
    relatedTerms: ['grind_size', 'brew_time'],
    relatedResourceTags: ['다이얼인', '문제해결', '워크스루', '입문'],
  },
  auto_manual_dosing: {
    id: 'auto_manual_dosing',
    term: 'AUTO / MANUAL dosing',
    koTerm: 'AUTO/MANUAL 도징',
    aliases: ['자동 도징', '수동 도징'],
    level: 'beginner',
    category: 'bes876',
    shortDefinition: '추출 방식이 아니라 원두를 얼마나 갈아 넣을지 잡는 방식입니다.',
    whyItMatters: 'AUTO는 도즈 게이지 보정 흐름을, MANUAL은 실측 도징량과 퍽 준비 일관성을 더 봐야 합니다.',
    whatToRecord: ['AUTO 또는 MANUAL', '실제 도징량 g', '도즈 게이지 또는 탬핑 후 퍽 사진'],
    commonMistake: 'AUTO/MANUAL을 샷 버튼이나 추출 모드로 착각하는 것입니다.',
    bes876Note: 'BES876에서는 어떤 모드를 쓰든 수율과 시간은 저울/타이머로 따로 기록하는 편이 좋습니다.',
    relatedTerms: ['dose', 'dose_gauge'],
    relatedResourceTags: ['AUTO', 'MANUAL', '도징', '매뉴얼', '다이얼인'],
  },
} as const satisfies Record<string, GlossaryEntry>;

export type GlossaryId = keyof typeof GLOSSARY_ENTRIES;

export const coreGlossaryIds = ['dose', 'yield', 'brew_time', 'grind_size'] as const satisfies readonly GlossaryId[];

const recommendedPolicy = {
  quick: ['dose', 'yield', 'brew_time', 'grind_size'],
  guided: [
    'dose',
    'yield',
    'brew_time',
    'grind_size',
    'single_wall',
    'dual_wall',
    'wdt',
    'leveling',
    'tamping',
    'puck_screen',
    'preinfusion',
    'first_drip',
    'channeling',
    'dose_gauge',
    'a_bit_more',
    'razor_trim',
    'pressure_gauge',
    'auto_manual_dosing',
  ],
  precision: ['preinfusion', 'first_drip', 'channeling', 'bottomless_check', 'pressure_gauge', 'puck_screen', 'wdt', 'tamping'],
} as const satisfies Record<RecordingMode, readonly GlossaryId[]>;

export const shouldShowGlossaryHelp = (
  id: GlossaryId,
  recordingMode: RecordingMode = 'guided',
  visibility: TermHelpVisibility = 'recommended'
) => {
  if (visibility === 'off') return false;
  if (visibility === 'full') return true;
  if (visibility === 'minimal') return (coreGlossaryIds as readonly GlossaryId[]).includes(id);
  return (recommendedPolicy[recordingMode] as readonly GlossaryId[]).includes(id);
};

export const getGlossaryEntry = (id: GlossaryId) => GLOSSARY_ENTRIES[id];
